=== idws-services/way4j_old/way4j/target/classes/way4j/tools/systemDefinitions/systemDefinitions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/NewXMLSchema" xmlns:w="http://www.example.org/NewXMLSchema" elementFormDefault="qualified">

<element name="system">
	<complexType>
		<choice maxOccurs="unbounded" minOccurs="0">
			<element name="configurations">
				<complexType mixed="true">
					<choice minOccurs="0" maxOccurs="unbounded">
						<element name="dataSource">
							<complexType>
								<choice maxOccurs="unbounded" minOccurs="0">
									<element name="hibernateProps">
										<complexType>
											<choice maxOccurs="unbounded" minOccurs="0">
												<element ref="w:property"/>
											</choice>
										</complexType>
									</element>
								</choice>
								<attribute name="user" use="required"/>
								<attribute name="password" use="required"/>
								<attribute name="url" use="required"/>
								<attribute name="driver" use="required"/>
							</complexType>
						</element>
						
						<element name="resourceLocations">
							<complexType>
								 <choice minOccurs="6" maxOccurs="6">
									<element name="model">
								 		<complexType>
								 			<attribute name="location" use="required"/>
								 		</complexType>
								 	</element>
								 	<element name="controller">
								 		<complexType>
								 			<attribute name="location" use="required"/>
								 		</complexType>
								 	</element>
								 	<element name="dao">
								 		<complexType>
								 			<attribute name="location" use="required"/>
								 		</complexType>
								 	</element>
								 	<element name="service">
								 		<complexType>
								 			<attribute name="location" use="required"/>
								 		</complexType>
								 	</element>
								 	<element name="lazyDataModel">
								 		<complexType>
								 			<attribute name="location" use="required"/>
								 		</complexType>
								 	</element>
								 	<element name="view">
								 		<complexType>
								 			<attribute name="location" use="required"/>
								 		</complexType>
								 	</element>
								 </choice>
							</complexType>
						</element>
						
					</choice>
					<attribute name="systemName"/>
				</complexType>
			</element>
			<element name="models">
				<complexType>
					<choice maxOccurs="unbounded" minOccurs="0">
						<element name="model"></element>
					</choice>
				</complexType>		
			</element>
		</choice>
	</complexType>
</element>

<!-- Elementos para heranÃ§a : -->

<element name="property">
	<complexType>
		<attribute name="name" use="required"/>
		<attribute name="value" use="required"/>
	</complexType>
</element>
	
    
</schema>

=== idws-services/way4j_old/way4j/src/main/java/systemConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<system xmlns="http://www.example.org/NewXMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/NewXMLSchema way4j/tools/systemBuild/systemDefinitions.xsd ">
	
	<configurations systemName="testApp">
		
		<dataSource user="postgresql" url="jdbc:postgresql://localhost:5432/idws_service_1" password="postgresql" driver="org.postgresql.Driver">
			<hibernateProps>
				 <property name="hibernate.dialect" value="org.hibernate.dialect.PostgreSQLDialect"/>
			</hibernateProps>
		</dataSource>
		
		<resourceLocations>
			<controller location="way4j.application.controller"/>
			<dao location="way4j.application.dao"/>
			<lazyDataModel location="way4j.application.view"/>
			<model location="way4j.application.model"/>
			<service location="way4j.application.service"/>
			<view location="way4j.application.view"/>
		</resourceLocations>
		
	</configurations>
	
	<models>
		<model></model>
	</models>
	
</system>
